---
- name: Deploy RevuHub Backend (Idempotent)
  hosts: backend
  become: yes
  vars:
    docker_image_tag: "{{ image_tag | default('latest') }}"

  tasks:

    # -----------------------------
    # Gather facts
    # -----------------------------
    - name: Gather facts
      ansible.builtin.setup:

    # -----------------------------
    # Clean old Docker sources/keyrings
    # -----------------------------
    - name: Remove old Docker list files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/docker.list
        - /etc/apt/sources.list.d/docker.list.save
        - /etc/apt/sources.list.d/docker.list.distUpgrade
        - /etc/apt/sources.list.d/docker.list.save.distUpgrade

    - name: Remove old Docker keyrings
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/keyrings/docker.gpg
        - /etc/apt/keyrings/docker.asc

    - name: Remove old Docker repo entries from sources.list
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb .*docker\.com'
        state: absent

    - name: Ensure /etc/apt/keyrings exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    # -----------------------------
    # Add Docker repo safely
    # -----------------------------
    - name: Download Docker GPG key
      ansible.builtin.command: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # -----------------------------
    # Install Docker & Compose
    # -----------------------------
    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    # -----------------------------
    # Backend deployment
    # -----------------------------
    - name: Ensure backend directory exists
      file:
        path: /home/ubuntu/backend
        state: directory

    - name: Copy production.env
      copy:
        content: "{{ production_env_content }}"
        dest: /home/ubuntu/production.env
        owner: ubuntu
        group: ubuntu
        mode: "0600"

    - name: Deploy Docker Compose file
      template:
        src: roles/backend/templates/docker-compose.yml.j2
        dest: /home/ubuntu/backend/docker-compose.yml

    - name: Start backend container
      command: docker-compose -f /home/ubuntu/backend/docker-compose.yml up -d
      args:
        chdir: /home/ubuntu/backend

    # -----------------------------
    # Nginx setup
    # -----------------------------
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy Nginx config
      copy:
        src: ../../nginx/revuhub.conf
        dest: /etc/nginx/sites-available/revuhub.conf

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/revuhub.conf
        dest: /etc/nginx/sites-enabled/revuhub.conf
        state: link

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
