- name: Deploy RevuHub Backend (Idempotent)
  hosts: backend
  become: yes
  vars:
    docker_image_tag: "{{ image_tag | default('latest') }}"
    backend_dir: /home/ubuntu/backend
    ecr_repo: 842676016170.dkr.ecr.ap-south-1.amazonaws.com/revuhub-backend
    aws_region: ap-south-1

  tasks:

    - name: Gather facts
      ansible.builtin.setup:

    - name: Remove old Docker list files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/docker.list
        - /etc/apt/sources.list.d/docker.list.save
        - /etc/apt/sources.list.d/docker.list.distUpgrade
        - /etc/apt/sources.list.d/docker.list.save.distUpgrade

    - name: Remove old Docker keyrings
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/keyrings/docker.gpg
        - /etc/apt/keyrings/docker.asc

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    - name: Install Docker using convenience script
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Ensure backend directory exists
      file:
        path: "{{ backend_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copy production.env
      copy:
        content: "{{ production_env_content }}"
        dest: /home/ubuntu/production.env
        owner: ubuntu
        group: ubuntu
        mode: "0600"

    - name: Deploy Docker Compose file
      template:
        src: roles/backend/templates/docker-compose.yml.j2
        dest: "{{ backend_dir }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"

       - name: Install unzip (required for AWS CLI)
        apt:
          name: unzip
          state: present
          update_cache: yes
      
      - name: Install AWS CLI v2
        shell: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
          unzip -o /tmp/awscliv2.zip -d /tmp
          sudo /tmp/aws/install
        args:
          creates: /usr/local/bin/aws
      
      - name: Login to AWS ECR
        shell: >
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 842676016170.dkr.ecr.ap-south-1.amazonaws.com/revuhub-backend
        args:
          executable: /bin/bash
  


    - name: Start backend container
      shell: docker-compose -f {{ backend_dir }}/docker-compose.yml up -d
      args:
        chdir: "{{ backend_dir }}"

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy Nginx config
      copy:
        src: ../../nginx/revuhub.conf
        dest: /etc/nginx/sites-available/revuhub.conf

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/revuhub.conf
        dest: /etc/nginx/sites-enabled/revuhub.conf
        state: link

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
