---
- name: Setup EC2 with Docker, Docker Compose, and Nginx
  hosts: all
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg

    - name: Ensure /etc/apt/keyrings exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker GPG key (idempotent)
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Create symlink for docker-compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy Nginx config
      copy:
        src: ./nginx/revuhub.conf
        dest: /etc/nginx/sites-available/revuhub.conf

    - name: Enable Nginx config
      file:
        src: /etc/nginx/sites-available/revuhub.conf
        dest: /etc/nginx/sites-enabled/revuhub.conf
        state: link
        force: yes

    - name: Test Nginx config
      command: nginx -t
      register: nginx_test
      ignore_errors: yes

    - name: Fail if Nginx config is invalid
      fail:
        msg: "Nginx configuration is invalid"
      when: nginx_test.rc != 0

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
